import Foundation

// MARK: - L10n — lightweight in-app localization
//
// Default: follow the Mac's system language (like the theme follows the
// system appearance). The user can override in Settings → General.
// Kept as simple dictionaries — no .lproj plumbing — so adding a language
// is one table.

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case english = "en"
    case italian = "it"

    var id: String { rawValue }

    var label: String {
        switch self {
        case .system:  return L10n.t("lang.system")
        case .english: return "English"
        case .italian: return "Italiano"
        }
    }
}

enum L10n {
    static let storageKey = "appLanguage"

    /// Effective 2-letter code: user override, else the system language.
    static var languageCode: String {
        let pref = UserDefaults.standard.string(forKey: storageKey) ?? "system"
        if pref != "system" { return pref }
        let sys = Locale.preferredLanguages.first ?? "en"
        return String(sys.prefix(2))
    }

    static var locale: Locale { Locale(identifier: languageCode) }

    static func t(_ key: String) -> String {
        if languageCode == "it", let s = it[key] { return s }
        return en[key] ?? key
    }

    // MARK: - Tables

    private static let en: [String: String] = [
        "lang.system": "System default",
        // Notes: code, Notes · Meetings
        "notes.fmt.inlineCode": "Inline code",
        "notes.fmt.codeBlock": "Code block",
        "notes.fmt.quote": "Block quote",
        "notes.kind.notes": "Notes",
        "notes.kind.meetings": "Meetings",
        "notes.sc.inlineCode": "Inline code in a note",
        "notes.sc.codeBlock": "Code block in a note",
        "notes.sc.quote": "Block quote in a note",
        "notes.sc.kind": "Notes \u{21C4} meeting notes",
        // U5 capture header
        "capture.placeholder": "Add a to-do\u{2026}",
        "capture.notePlaceholder": "Write a note\u{2026}",
        "capture.save": "Save",
        "capture.tab": "tab",
        "nav.backTo": "Back to %@",
        "todo.sc.clearDraft": "Clear the field \u{00B7} back one level \u{00B7} close",
        // Onboarding (Direction B)
        "ob.welcome.tagline": "Your to-dos and today\u{2019}s meetings, always in reach of the notch.",
        "ob.start": "Start setup",
        "ob.continue": "Continue",
        "ob.openOtto": "Open Otto",
        "ob.back": "Back",
        "notes.fmt.image": "Add image",
        "attach.open": "Open image",
        "attach.remove": "Remove image",
        "attach.a11y": "Image",
        "attach.copy": "Copy image",
        "todo.sc.addImage": "Add an image (note or to-do)",
        "cal.faster.title": "Get last-minute meetings sooner",
        "cal.faster.steps": "In Calendar, open Settings \u{203A} Accounts, choose your Google account and set Refresh Calendars to Every minute. A meeting booked at the last minute then shows up within about a minute.",
        "cal.faster.open": "Open Calendar",
        "ob.next": "Next",
        "ob.discover.title": "Everything, one hover away.",
        "ob.discover.body": "Otto keeps three things within reach of the notch. Have a look around.",
        "ob.discover.tasks": "Tasks",
        "ob.discover.tasks.caption": "Capture a to-do in a second, from any app.",
        "ob.discover.notes": "Notes",
        "ob.discover.notes.caption": "Jot things down without opening another app.",
        "ob.discover.meetings": "Meetings",
        "ob.discover.meetings.caption": "See what\u{2019}s next and join with one key.",
        "ob.style.title": "How do you want Otto?",
        "ob.style.body": "Pick where Otto lives. Both work the same way.",
        "ob.style.notch": "In the notch",
        "ob.style.notch.caption": "Lives in the notch. Hover the top of the screen to open it.",
        "ob.style.floating": "Floating panel",
        "ob.style.floating.caption": "A panel in the middle of the screen, opened with a shortcut.",
        "ob.style.footnote": "You can switch anytime in Settings.",
        "ob.shortcut.press": "Press the three keys together",
        "ob.shortcut.gotIt": "Got it. Works from any app.",
        "ob.shortcut.fallback": "Shortcut taken by another app? Continue anyway.",
        "ob.pv.task1": "Send the Q3 deck to Simon",
        "ob.pv.task2": "Book dentist",
        "ob.pv.task3": "Buy oat milk",
        "ob.pv.noteTitle": "Monday sync",
        "ob.pv.saved": "Saved",
        "ob.pv.noteAgenda": "Agenda for Monday",
        "ob.pv.noteLine1": "Q4 priorities",
        "ob.pv.noteLine2": "Hiring update from Matt",
        "ob.pv.noteLine3": "Launch date with Simon",
        "ob.pv.words": "12 words",
        "ob.pv.meeting": "Weekly product sync",
        "ob.pv.inMinutes": "in 34 min",
        "ob.pv.join": "Join",
        "ob.pv.snooze": "Snooze",
        "ob.pv.whatNeedsDoing": "What needs doing?",
        "ob.pv.addTodo": "Add a to-do\u{2026}",
        "ob.pv.work": "Work",
        "ob.pv.personal": "Personal",
        "ob.pv.todo1": "Send the proposal to Simon",
        "ob.pv.todo2": "Review Matt\u{2019}s feedback",
        "ob.pv.todo3": "Prep for Monday\u{2019}s standup",
        "ob.pv.step1": "Collect updates from the team",
        "ob.pv.step2": "Write the agenda",
        "ob.pv.moreSteps": "2 more steps",
        "ob.progress": "Step %d of %d",
        "ob.shortcut.title": "Add a to-do from anywhere.",
        "ob.shortcut.body": "Press the shortcut in any app, type, hit return. You\u{2019}re back where you were.",
        "ob.shortcut.keysLabel": "Control, Shift, N",
        "ob.perm.title": "Connect your day.",
        "ob.perm.body": "Read-only. Your to-dos, notes and calendar never leave this Mac. Skip anything and the rest still works.",
        "ob.perm.calendar": "Calendar",
        "ob.perm.calendar.caption": "Heads-up before meetings",
        "ob.perm.login": "Open at login",
        "ob.perm.login.caption": "Ready when you sign in",
        "ob.perm.usage": "Share usage data",
        "ob.perm.usage.caption": "Anonymous. Never your to-dos or notes",
        "privacy.subtitle": "Anonymous usage data helps improve Otto: which features are used and where the setup stalls. Never your to-dos, notes, calendar or anything you type.",
        "privacy.toggle": "Share anonymous usage data",
        "privacy.show": "Show what is sent",
        "privacy.reset": "Reset ID",
        "privacy.id": "Anonymous ID",
        "feedback.menu": "Send feedback",
        "feedback.title": "Send Feedback",
        "feedback.subtitle": "Tell us what works, what does not, and what you would like to see.",
        "feedback.category": "Category",
        "feedback.cat.bug": "Bug",
        "feedback.cat.idea": "Idea",
        "feedback.cat.love": "Something I like",
        "feedback.cat.other": "Other",
        "feedback.description": "Description",
        "feedback.placeholder.bug": "What happened? What did you expect?",
        "feedback.placeholder.idea": "What would you like Otto to do?",
        "feedback.placeholder.love": "What do you like about Otto?",
        "feedback.placeholder.other": "Tell us anything",
        "feedback.required": "Required. A few words are enough.",
        "feedback.attach": "Attach files",
        "feedback.drop": "Browse files, or drop them here",
        "feedback.dropHint": "Screenshots, recordings, text or PDF — up to 5 files",
        "feedback.diagnostics": "Include diagnostic info",
        "feedback.cancel": "Cancel",
        "feedback.send": "Send Feedback",
        "feedback.email": "Email (optional)",
        "feedback.emailPlaceholder": "If you would like a reply",
        "feedback.privacyNote": "Sent to Otto\u{2019}s developer. Not stored on any server.",
        "feedback.sent": "Thanks \u{2014} sent.",
        "feedback.queued": "You\u{2019}re offline. It will be sent when you\u{2019}re back online.",
        "feedback.tooLarge": "The attachments are over 10 MB in total. Remove one and try again.",
        "ob.perm.grant": "Grant",
        "ob.perm.granted": "Granted",
        "ob.perm.openSettings": "Open Settings",
        "ob.perm.found1": "Found %d calendar",
        "ob.perm.foundN": "Found %d calendars",
        "ob.perm.nextUp": "next up: %@ at %@",
        "ob.done.title": "You\u{2019}re set.",
        "ob.done.body": "Otto stays quiet until you need it. A few things worth remembering:",
        "ob.done.add": "Add a to-do from anywhere",
        "ob.done.search": "Search every list",
        "ob.done.shortcuts": "See every shortcut",
        // Filters
        // Notch
        // Actions
        "action.delete": "Delete",
        "action.moveLeft": "Move Left",
        "action.moveRight": "Move Right",
        // Snippets
        "snippet.cancel": "Cancel",
        // Notes
        "filter.notes": "Notes",
        "filter.calendar": "Calendar",
        // Notes space
        "notes.composerPlaceholder": "What's on your mind?",
        "notes.save": "Save",
        "notes.saved": "Saved",
        "notes.saving": "Saving\u{2026}",
        "calendar.emptyTitle": "No meeting notes yet",
        "calendar.emptyBody": "Open notes from a meeting and they are kept here.",
        "notes.rename": "Rename",
        "notes.duplicate": "Duplicate",
        "notes.download": "Download .md",
        "notes.wordsSuffix": "words",
        "notes.deletedSuffix": "deleted",
        "notes.undo": "Undo",
        "notes.back": "Back to notes",
        "notes.fmt.title": "Title",
        "notes.fmt.subtitle": "Subtitle",
        "notes.fmt.body": "Body",
        "notes.fmt.bulleted": "Bulleted list",
        "notes.fmt.numbered": "Numbered list",
        "notes.fmt.checklist": "Checklist",
        "todo.sc.format": "Format the note",
        "todo.sc.nestList": "Nest / un-nest a list row",
        "notes.justNow": "just now",
        "notes.yesterday": "yesterday",
        "notes.dateTitle": "Note of",
        "todo.sc.notes": "Notes space",
        // To-dos
        "todo.completed": "Completed",
        "todo.todayLabel": "Today",
        "todo.yesterdayLabel": "Yesterday",
        "todo.archivedHint": "Archived \u{2014} kept in the Archive folder, no longer editable here",
        "todo.sc.toggleCompleted": "Show / hide Completed",
        "todo.sc.toggleAllDays": "Open / close every day",
        "todo.sc.insights": "Insights",
        "todo.showAll": "Show all",
        "todo.showFewer": "Show fewer",
        "todo.untickHint": "Click to put it back in the list",
        "insights.title": "Insights",
        "insights.lastTwelveMonths": "Last 12 months",
        "insights.closed": "closed",
        "insights.closedThisWeek": "closed this week",
        "insights.leftBehind": "Left behind",
        "insights.open": "open",
        "insights.more": "%@ more",
        "insights.empty": "Finish something and this page starts filling in.",
        "insights.lastWeek": "%@ closed last week",
        "insights.view": "View",
        "insights.today": "today",
        "insights.dayShort": " d",
        "menu.preferences": "Preferences",
        "menu.shortcuts": "Keyboard shortcuts",
        "menu.notesFolder": "Notes folder",
        "menu.quit": "Quit Otto",
        "meeting.notes": "Notes",
        "meeting.openNotes": "Open notes",
        "meeting.search": "Search meeting notes",
        "meeting.choose": "Meeting notes",
        "meeting.noEvents": "No upcoming meetings",
        "meeting.previous": "Previous sessions",
        "meeting.link": "Link conversation",
        "meeting.noSessions": "No sessions found",
        "meeting.tasks": "Session to-dos",
        "meeting.chooseList": "Choose list",
        "meeting.taskPlaceholder": "Write a to-do…",
        "meeting.openPrevious": "Previous open actions",
        "meeting.completed": "Completed",
        "meeting.archiveUnavailable": "Completed history unavailable",
        "meeting.deletedNote": "Deleted note",
        "meeting.mirrorFailed": "Markdown copy unavailable; local notes are kept.",
        "meeting.retry": "Retry",
        "meeting.saveFailed": "Unable to save",
        "meeting.recoveryFailed": "Notes could not be recovered. Original files were preserved.",
        "meeting.recovered": "Notes recovered from backup. Save to retry.",
        "meeting.focusShortcut": "Meeting: body / draft / tasks / controls",
        "meeting.contextShortcut": "Meeting: history / link / open / completed / undo",
        "meeting.searchShortcut": "Search meeting notes",
        "notes.action.addTo": "Add to",
        "notes.action.add": "Add as to-do",
        "notes.action.notATask": "Not a task",
        "notes.action.found": "%@ action items found",
        "notes.action.foundOne": "1 action item found",
        "notes.sc.pickerKeys": "Choose section · confirm · cancel",
        "notes.sc.actionPicker": "Selection → to-do / toggle linked task",
        "todo.sc.preferences": "Preferences",
        "todo.sc.quit": "Quit Otto",
        "todo.editTitle": "Edit text",
        "settings.open": "Settings",
        "todo.emptyTitle": "All clear in here",
        "todo.emptySubtitle": "Otto is peeking for your next to-do.",
        "todo.emptyA11y": "Empty list.",
        "notes.emptySubtitle": "Otto is peeking for your next note.",
        "todo.titlePlaceholder": "What needs doing?",
        "todo.create": "Create",
        "todo.newCollection": "New collection",
        "todo.newSection": "New section",
        "todo.sc.newSection": "New section",
        "todo.moveTo": "Move to\u{2026}",
        "todo.searchCollections": "Search collections\u{2026}",
        "todo.shortcuts": "Keyboard shortcuts",
        "todo.sc.quickEntry": "Quick entry (from anywhere)",
        "todo.sc.newTodo": "New to-do (in app)",
        "todo.sc.switchCollection": "Switch collection",
        "todo.sc.moveFocus": "Move between to-dos",
        "todo.sc.reorder": "Reorder within the list",
        "todo.sc.expandRow": "Details, or switch section",
        "todo.sc.closeHint": "press ? again to close",
        "cal.with": "with",
        "cal.join": "Join",
        "cal.snoozeShort": "Snooze",
        "cal.snoozeAutoHint": "Snoozes itself if you leave it \u{2014} hover to hold",
        "cal.joinHelp": "Open the video call",
        "cal.snooze": "Snooze %dm",
        "cal.startingIn": "Starting in %d min",
        // Short form for the meeting card's top-right countdown ("in 34 min").
        "cal.inMinutes": "in %d min",
        "cal.inHours": "in %dh %dm",
        "cal.now": "now",
        "cal.startingNow": "Starting now",
        "cal.untitled": "(No title)",
        "cal.nudgeTitle": "See today's meetings here",
        "cal.nudgeSubtitle": "Connect your calendar in Settings",
        "todo.clearCompleted": "Clear completed",
        "update.section": "Updates",
        "update.check": "Check for Updates\u{2026}",
        "update.checking": "Checking\u{2026}",
        "update.automatic": "Check automatically",
        "update.lastChecked": "Last checked %@",
        "update.neverChecked": "not yet",
        "update.version": "Version %@",
        "cal.err.deniedDetail": "macOS refused calendar access (status: %1$@, app: %2$@). If the Calendars list shows Otto as allowed, that entry belongs to an older copy \u{2014} run  tccutil reset Calendar %2$@  in Terminal, then reopen Otto.",
        "cal.err.deniedRecoverDetail": "macOS is refusing calendar access and will not re-ask (status: %1$@, app: %2$@). In Terminal run:  tccutil reset Calendar %2$@  then reopen Otto from Applications.",
        "integrity.translocated": "macOS is running Otto from a temporary read-only copy, so it cannot ask for calendar access. Move Otto to your Applications folder, then open it from there.",
        "integrity.quarantined": "macOS has Otto quarantined as a downloaded app, so it cannot ask for calendar access. Move it to Applications, then right-click it \u{203A} Open once to clear the quarantine.",
        "cal.err.noCalendars": "No calendars found. Add your account in System Settings \u{203A} Internet Accounts, then try again.",
        "todo.categoryName": "Name",
        "todo.matches": "Matches",
        "todo.noMatches": "No matches.",
        "todo.inCategory": "in",
        "todo.notePlaceholder": "Add a note\u{2026}",
        "todo.stepPlaceholder": "Type to add a step",
        "todo.oneMoreStep": "1 more step",
        "todo.moreSteps": "%@ more steps",
        "todo.switchSection": "Switch section",
        "todo.switchSpace": "Switch space",
        "presence.in": "in",
        "presence.now": "now",
        "key.tab": "Tab",
        "date.today": "Today",
        "date.tomorrow": "Tomorrow",
        "todo.sc.toggleComplete": "Complete / uncomplete",
        "todo.sc.completeOrJoin": "Complete the selected to-do, or join the next meeting",
        "todo.sc.editTitle": "Edit the focused to-do",
        "todo.sc.moveItem": "Move to another collection",
        // Settings
        "settings.language": "Language",
        "settings.language.subtitle": "Follows your Mac's language by default.",
    ]

    private static let it: [String: String] = [
        "lang.system": "Predefinita di sistema",
        // Notes: code, Notes · Meetings
        "notes.fmt.inlineCode": "Codice inline",
        "notes.fmt.codeBlock": "Blocco di codice",
        "notes.fmt.quote": "Citazione",
        "notes.kind.notes": "Note",
        "notes.kind.meetings": "Riunioni",
        "notes.sc.inlineCode": "Codice inline in una nota",
        "notes.sc.codeBlock": "Blocco di codice in una nota",
        "notes.sc.quote": "Citazione in una nota",
        "notes.sc.kind": "Note \u{21C4} note delle riunioni",
        // U5 capture header
        "capture.placeholder": "Aggiungi un to-do\u{2026}",
        "capture.notePlaceholder": "Scrivi una nota\u{2026}",
        "capture.save": "Salva",
        "capture.tab": "tab",
        "nav.backTo": "Torna a %@",
        "todo.sc.clearDraft": "Svuota il campo \u{00B7} indietro di un livello \u{00B7} chiudi",
        // Onboarding (Direction B)
        "ob.welcome.tagline": "I tuoi to-do e le riunioni di oggi, sempre a portata di notch.",
        "ob.start": "Inizia",
        "ob.continue": "Continua",
        "ob.openOtto": "Apri Otto",
        "ob.back": "Indietro",
        "notes.fmt.image": "Aggiungi immagine",
        "attach.open": "Apri immagine",
        "attach.remove": "Rimuovi immagine",
        "attach.a11y": "Immagine",
        "attach.copy": "Copia immagine",
        "todo.sc.addImage": "Aggiungi un\u{2019}immagine (nota o to-do)",
        "cal.faster.title": "Ricevi prima le riunioni dell\u{2019}ultimo minuto",
        "cal.faster.steps": "In Calendario apri Impostazioni \u{203A} Account, scegli il tuo account Google e imposta Aggiorna calendari su Ogni minuto. Una riunione fissata all\u{2019}ultimo compare cos\u{00EC} entro circa un minuto.",
        "cal.faster.open": "Apri Calendario",
        "ob.next": "Avanti",
        "ob.discover.title": "Tutto a portata di notch.",
        "ob.discover.body": "Otto tiene tre cose a portata di notch. Dai un\u{2019}occhiata.",
        "ob.discover.tasks": "To-do",
        "ob.discover.tasks.caption": "Annota un to-do in un attimo, da qualsiasi app.",
        "ob.discover.notes": "Note",
        "ob.discover.notes.caption": "Prendi appunti senza aprire un\u{2019}altra app.",
        "ob.discover.meetings": "Riunioni",
        "ob.discover.meetings.caption": "Vedi cosa c\u{2019}\u{00E8} dopo ed entra con un tasto.",
        "ob.style.title": "Dove vuoi Otto?",
        "ob.style.body": "Scegli dove vive Otto. Funzionano allo stesso modo.",
        "ob.style.notch": "Nel notch",
        "ob.style.notch.caption": "Vive nel notch. Porta il cursore in cima allo schermo per aprirlo.",
        "ob.style.floating": "Pannello flottante",
        "ob.style.floating.caption": "Un pannello al centro dello schermo, aperto con una scorciatoia.",
        "ob.style.footnote": "Puoi cambiarlo quando vuoi nelle Impostazioni.",
        "ob.shortcut.press": "Premi i tre tasti insieme",
        "ob.shortcut.gotIt": "Fatto. Funziona da qualsiasi app.",
        "ob.shortcut.fallback": "Scorciatoia gi\u{00E0} usata da un\u{2019}altra app? Continua comunque.",
        "ob.pv.task1": "Inviare la presentazione Q3 a Simon",
        "ob.pv.task2": "Prenotare il dentista",
        "ob.pv.task3": "Comprare latte d\u{2019}avena",
        "ob.pv.noteTitle": "Riunione del luned\u{00EC}",
        "ob.pv.saved": "Salvata",
        "ob.pv.noteAgenda": "Ordine del giorno",
        "ob.pv.noteLine1": "Priorit\u{00E0} del Q4",
        "ob.pv.noteLine2": "Aggiornamento assunzioni da Matt",
        "ob.pv.noteLine3": "Data di lancio con Simon",
        "ob.pv.words": "12 parole",
        "ob.pv.meeting": "Sync settimanale di prodotto",
        "ob.pv.inMinutes": "tra 34 min",
        "ob.pv.join": "Entra",
        "ob.pv.snooze": "Posticipa",
        "ob.pv.whatNeedsDoing": "Cosa c\u{2019}\u{00E8} da fare?",
        "ob.pv.addTodo": "Aggiungi un to-do\u{2026}",
        "ob.pv.work": "Lavoro",
        "ob.pv.personal": "Personale",
        "ob.pv.todo1": "Inviare la proposta a Simon",
        "ob.pv.todo2": "Rivedere il feedback di Matt",
        "ob.pv.todo3": "Preparare lo standup del luned\u{00EC}",
        "ob.pv.step1": "Raccogliere gli aggiornamenti",
        "ob.pv.step2": "Scrivere l\u{2019}agenda",
        "ob.pv.moreSteps": "altri 2 passi",
        "ob.progress": "Passo %d di %d",
        "ob.shortcut.title": "Aggiungi un to-do da ovunque.",
        "ob.shortcut.body": "Premi la scorciatoia in qualsiasi app, scrivi, premi invio. Torni dov\u{2019}eri.",
        "ob.shortcut.keysLabel": "Control, Maiuscole, N",
        "ob.perm.title": "Collega la tua giornata.",
        "ob.perm.body": "Solo lettura. I tuoi to-do, le note e il calendario non lasciano mai questo Mac. Salta quello che vuoi: il resto funziona lo stesso.",
        "ob.perm.calendar": "Calendario",
        "ob.perm.calendar.caption": "Avviso prima delle riunioni",
        "ob.perm.login": "Apri al login",
        "ob.perm.login.caption": "Pronto quando accedi",
        "ob.perm.usage": "Condividi dati d\u{2019}uso",
        "ob.perm.usage.caption": "Anonimi. Mai i tuoi to-do o le note",
        "privacy.subtitle": "I dati d\u{2019}uso anonimi aiutano a migliorare Otto: quali funzioni si usano e dove l\u{2019}onboarding si blocca. Mai i tuoi to-do, le note, il calendario o qualsiasi cosa scrivi.",
        "privacy.toggle": "Condividi dati d\u{2019}uso anonimi",
        "privacy.show": "Mostra cosa viene inviato",
        "privacy.reset": "Reimposta ID",
        "privacy.id": "ID anonimo",
        "feedback.menu": "Invia feedback",
        "feedback.title": "Invia feedback",
        "feedback.subtitle": "Dicci cosa funziona, cosa no e cosa vorresti vedere.",
        "feedback.category": "Categoria",
        "feedback.cat.bug": "Bug",
        "feedback.cat.idea": "Idea",
        "feedback.cat.love": "Qualcosa che mi piace",
        "feedback.cat.other": "Altro",
        "feedback.description": "Descrizione",
        "feedback.placeholder.bug": "Cosa \u{00E8} successo? Cosa ti aspettavi?",
        "feedback.placeholder.idea": "Cosa vorresti che facesse Otto?",
        "feedback.placeholder.love": "Cosa ti piace di Otto?",
        "feedback.placeholder.other": "Scrivi quello che vuoi",
        "feedback.required": "Obbligatoria. Bastano poche parole.",
        "feedback.attach": "Allega file",
        "feedback.drop": "Sfoglia i file, o trascinali qui",
        "feedback.dropHint": "Screenshot, registrazioni, testo o PDF \u{2014} fino a 5 file",
        "feedback.diagnostics": "Includi info diagnostiche",
        "feedback.cancel": "Annulla",
        "feedback.send": "Invia feedback",
        "feedback.email": "Email (facoltativa)",
        "feedback.emailPlaceholder": "Se vuoi una risposta",
        "feedback.privacyNote": "Inviato allo sviluppatore di Otto. Non viene conservato su nessun server.",
        "feedback.sent": "Grazie \u{2014} inviato.",
        "feedback.queued": "Sei offline. Verr\u{00E0} inviato quando torni online.",
        "feedback.tooLarge": "Gli allegati superano 10 MB in totale. Togline uno e riprova.",
        "ob.perm.grant": "Consenti",
        "ob.perm.granted": "Consentito",
        "ob.perm.openSettings": "Apri Impostazioni",
        "ob.perm.found1": "Trovato %d calendario",
        "ob.perm.foundN": "Trovati %d calendari",
        "ob.perm.nextUp": "prossima: %@ alle %@",
        "ob.done.title": "Tutto pronto.",
        "ob.done.body": "Otto resta in silenzio finch\u{00E9} non ti serve. Qualche cosa da ricordare:",
        "ob.done.add": "Aggiungi un to-do da ovunque",
        "ob.done.search": "Cerca in tutte le liste",
        "ob.done.shortcuts": "Vedi tutte le scorciatoie",
        "action.delete": "Elimina",
        "action.moveLeft": "Sposta a sinistra",
        "action.moveRight": "Sposta a destra",
        "snippet.cancel": "Annulla",
        "filter.notes": "Note",
        "filter.calendar": "Calendario",
        // Spazio Note
        "notes.composerPlaceholder": "A cosa stai pensando?",
        "notes.save": "Salva",
        "notes.saved": "Salvato",
        "notes.saving": "Salvataggio\u{2026}",
        "calendar.emptyTitle": "Ancora nessuna nota di riunione",
        "calendar.emptyBody": "Apri le note da una riunione: le ritrovi qui.",
        "notes.rename": "Rinomina",
        "notes.duplicate": "Duplica",
        "notes.download": "Scarica .md",
        "notes.wordsSuffix": "parole",
        "notes.deletedSuffix": "eliminata",
        "notes.undo": "Annulla",
        "notes.back": "Torna alle note",
        "notes.fmt.title": "Titolo",
        "notes.fmt.subtitle": "Sottotitolo",
        "notes.fmt.body": "Corpo",
        "notes.fmt.bulleted": "Elenco puntato",
        "notes.fmt.numbered": "Elenco numerato",
        "notes.fmt.checklist": "Spunte",
        "todo.sc.format": "Formatta la nota",
        "todo.sc.nestList": "Rientra / sporgi una riga di elenco",
        "notes.justNow": "adesso",
        "notes.yesterday": "ieri",
        "notes.dateTitle": "Note del",
        "todo.sc.notes": "Spazio Note",
        "todo.completed": "Completati",
        "todo.todayLabel": "Oggi",
        "todo.yesterdayLabel": "Ieri",
        "todo.archivedHint": "Archiviato \u{2014} conservato nella cartella Archive, qui non pi\u{00F9} modificabile",
        "todo.sc.toggleCompleted": "Mostra / nascondi Completati",
        "todo.sc.toggleAllDays": "Apri / chiudi tutti i giorni",
        "todo.sc.insights": "Insights",
        "todo.showAll": "Mostra tutto",
        "todo.showFewer": "Mostra meno",
        "todo.untickHint": "Clicca per rimetterlo nella lista",
        "insights.title": "Insights",
        "insights.lastTwelveMonths": "Ultimi 12 mesi",
        "insights.closed": "chiusi",
        "insights.closedThisWeek": "chiusi questa settimana",
        "insights.leftBehind": "Rimasti indietro",
        "insights.open": "aperti",
        "insights.more": "Altri %@",
        "insights.empty": "Chiudi qualcosa e questa pagina inizia a riempirsi.",
        "insights.lastWeek": "%@ chiusi la settimana scorsa",
        "insights.view": "Vedi",
        "insights.today": "oggi",
        "insights.dayShort": " g",
        "menu.preferences": "Preferenze",
        "menu.shortcuts": "Scorciatoie",
        "menu.notesFolder": "Cartella delle note",
        "menu.quit": "Esci da Otto",
        "meeting.notes": "Note",
        "meeting.openNotes": "Apri note",
        "meeting.search": "Cerca nelle note meeting",
        "meeting.choose": "Note meeting",
        "meeting.noEvents": "Nessun meeting imminente",
        "meeting.previous": "Sessioni precedenti",
        "meeting.link": "Collega conversazione",
        "meeting.noSessions": "Nessuna sessione trovata",
        "meeting.tasks": "To-do della sessione",
        "meeting.chooseList": "Scegli lista",
        "meeting.taskPlaceholder": "Scrivi un to-do…",
        "meeting.openPrevious": "Azioni aperte precedenti",
        "meeting.completed": "Completati",
        "meeting.archiveUnavailable": "Storico completati non disponibile",
        "meeting.deletedNote": "Nota eliminata",
        "meeting.mirrorFailed": "Copia Markdown non disponibile; le note locali sono conservate.",
        "meeting.retry": "Riprova",
        "meeting.saveFailed": "Impossibile salvare",
        "meeting.recoveryFailed": "Impossibile recuperare le note. I file originali sono stati conservati.",
        "meeting.recovered": "Note recuperate dal backup. Salva per riprovare.",
        "meeting.focusShortcut": "Meeting: corpo / bozza / task / controlli",
        "meeting.contextShortcut": "Meeting: storico / collega / aperti / completati / annulla",
        "meeting.searchShortcut": "Cerca note meeting",
        "notes.action.addTo": "Aggiungi a",
        "notes.action.add": "Aggiungi come to-do",
        "notes.action.notATask": "Non \u{00E8} un impegno",
        "notes.action.found": "%@ impegni trovati",
        "notes.action.foundOne": "1 impegno trovato",
        "notes.sc.pickerKeys": "Scegli sezione · conferma · annulla",
        "notes.sc.actionPicker": "Selezione → to-do / completa collegato",
        "todo.sc.preferences": "Preferenze",
        "todo.sc.quit": "Esci da Otto",
        "todo.editTitle": "Modifica testo",
        "settings.open": "Impostazioni",
        "todo.emptyTitle": "Tutto in ordine qui",
        "todo.emptySubtitle": "Otto sbircia in attesa del tuo prossimo to-do.",
        "todo.emptyA11y": "Lista vuota.",
        "notes.emptySubtitle": "Otto sbircia in attesa della tua prossima nota.",
        "todo.titlePlaceholder": "Cosa c'\u{00E8} da fare?",
        "todo.create": "Crea",
        "todo.newCollection": "Nuova raccolta",
        "todo.newSection": "Nuova sezione",
        "todo.sc.newSection": "Nuova sezione",
        "todo.moveTo": "Sposta in\u{2026}",
        "todo.searchCollections": "Cerca raccolte\u{2026}",
        "todo.shortcuts": "Scorciatoie da tastiera",
        "todo.sc.quickEntry": "Inserimento rapido (ovunque)",
        "todo.sc.newTodo": "Nuovo to-do (nell'app)",
        "todo.sc.switchCollection": "Cambia raccolta",
        "todo.sc.moveFocus": "Naviga tra i to-do",
        "todo.sc.reorder": "Riordina nella lista",
        "todo.sc.expandRow": "Dettagli, o cambia sezione",
        "todo.sc.closeHint": "premi ? per chiudere",
        "cal.with": "con",
        "cal.join": "Partecipa",
        "cal.snoozeShort": "Rinvia",
        "cal.snoozeAutoHint": "Si rinvia da solo \u{2014} passa il mouse per fermarlo",
        "todo.clearCompleted": "Cancella completati",
        "update.section": "Aggiornamenti",
        "update.check": "Cerca aggiornamenti\u{2026}",
        "update.checking": "Controllo\u{2026}",
        "update.automatic": "Controlla automaticamente",
        "update.lastChecked": "Ultimo controllo %@",
        "update.neverChecked": "mai",
        "update.version": "Versione %@",
        "integrity.translocated": "macOS sta eseguendo Otto da una copia temporanea in sola lettura, quindi non pu\u{00F2} chiedere l'accesso al calendario. Sposta Otto nella cartella Applicazioni e aprilo da l\u{00EC}.",
        "integrity.quarantined": "macOS tiene Otto in quarantena come app scaricata, quindi non pu\u{00F2} chiedere l'accesso al calendario. Spostalo in Applicazioni, poi fai clic destro \u{203A} Apri una volta per togliere la quarantena.",
        "cal.inMinutes": "tra %d min",
        "cal.inHours": "tra %dh %dm",
        "cal.now": "ora",
        "cal.joinHelp": "Apri la videochiamata",
        "cal.snooze": "Rimanda %dm",
        "cal.startingIn": "Inizia tra %d min",
        "cal.startingNow": "Sta iniziando",
        "cal.untitled": "(Senza titolo)",
        "cal.nudgeTitle": "Vedi qui le riunioni di oggi",
        "cal.nudgeSubtitle": "Collega il calendario nelle Impostazioni",
        "cal.err.deniedDetail": "macOS ha rifiutato l'accesso al calendario (stato: %1$@, app: %2$@). Se nell'elenco Calendari Otto risulta consentito, quella voce appartiene a una copia pi\u{00F9} vecchia: esegui  tccutil reset Calendar %2$@  nel Terminale e riapri Otto.",
        "cal.err.deniedRecoverDetail": "macOS rifiuta l'accesso e non lo richiede pi\u{00F9} (stato: %1$@, app: %2$@). Nel Terminale esegui:  tccutil reset Calendar %2$@  poi riapri Otto da Applicazioni.",
        "cal.err.noCalendars": "Nessun calendario trovato. Aggiungi il tuo account in Impostazioni di Sistema \u{203A} Account Internet, poi riprova.",
        "todo.categoryName": "Nome",
        "todo.matches": "Risultati",
        "todo.noMatches": "Nessun risultato.",
        "todo.inCategory": "in",
        "todo.notePlaceholder": "Aggiungi una nota\u{2026}",
        "todo.stepPlaceholder": "Scrivi per aggiungere un passaggio",
        "todo.oneMoreStep": "1 altro passaggio",
        "todo.moreSteps": "%@ passaggi in più",
        "todo.switchSection": "Cambia sezione",
        "todo.switchSpace": "Cambia spazio",
        "presence.in": "tra",
        "presence.now": "ora",
        "key.tab": "Tab",
        "date.today": "Oggi",
        "date.tomorrow": "Domani",
        "todo.sc.toggleComplete": "Completa / annulla",
        "todo.sc.completeOrJoin": "Completa il to-do selezionato, o entra nel prossimo meeting",
        "todo.sc.editTitle": "Modifica il to-do selezionato",
        "todo.sc.moveItem": "Sposta in un'altra raccolta",
        "settings.language": "Language",
        "settings.language.subtitle": "Segue la lingua del Mac per impostazione predefinita.",
    ]
}
