import AppKit
import UniformTypeIdentifiers

// MARK: - ClipboardMonitor — retired compatibility boundary
//
// NSPasteboard has no notification API — polling changeCount at 0.5s is the
// standard approach (Maccy, Pasta, etc.).
//
// Only DELIBERATE copies are recorded. Dictation tools (Wispr Flow, Handy…)
// write to the pasteboard programmatically on every utterance and would spam
// the notch. Two guards:
//   1. Items marked transient/concealed via the org.nspasteboard.* convention
//      (password managers, dictation tools) are always ignored.
//   2. A change is only recorded if the user pressed ⌘C / ⌘X shortly before —
//      that's the signature of a real "I want this" copy.

@MainActor
class ClipboardMonitor: ObservableObject {
    static let shared = ClipboardMonitor()
    private static let monitoringIsAvailable = false

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private var skipNext: Bool = false

    // Timestamp of the last ⌘C/⌘X — a pasteboard change within this window
    // counts as a user copy; anything else is programmatic noise.
    private var lastCopyKeystroke: Date = .distantPast
    private let copyWindow: TimeInterval = 3.0
    private var keyMonitor: Any?

    // Pasteboard-marker convention: http://nspasteboard.org
    private static let ignoredMarkers: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    func startMonitoring() {
        // Clipboard history and its global ⌘C/⌘X observer belonged to
        // NotchSnap. Otto deliberately leaves the pasteboard alone.
        stopMonitoring()
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
        if let m = keyMonitor { NSEvent.removeMonitor(m); keyMonitor = nil }
    }

    /// Call this before programmatically writing to the pasteboard (e.g., Quick Copy)
    /// so the monitor doesn't add a duplicate item.
    func skipNextChange() {
        skipNext = true
    }

    private func checkForChanges() {
        // A defensive boundary for any old caller left in a migration build.
        // No clipboard data may enter Otto after the product pivot.
        guard Self.monitoringIsAvailable else { return }
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if skipNext {
            skipNext = false
            return
        }

        // Guard 1: explicit "don't record me" markers.
        if let types = pb.types, Self.ignoredMarkers.contains(where: types.contains) {
            return
        }

        // Guard 2: no recent ⌘C/⌘X → programmatic write (dictation, auto-fill,
        // scripts). Screenshots are exempt — they arrive via the system's
        // screencapture pasteboard type without a keystroke.
        let isScreenshot = pb.types?.contains(.init("com.apple.screencapture")) == true
        let isUserCopy = Date().timeIntervalSince(lastCopyKeystroke) < copyWindow
        guard isUserCopy || isScreenshot else { return }

        // Classify and add to gallery
        if let item = ClipboardItem.fromPasteboard(pb) {
            AppState.shared.addClipboardItem(item)
            NotchController.shared.triggerClipboardNotification(item: item)
        }
    }
}
